# Generated by Django 2.2.1 on 2019-05-31 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=50, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 5, 31, 9, 46, 13, 557350, tzinfo=utc))),
                ('bloodgrp', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
