# Generated by Django 2.2.1 on 2019-05-31 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bloody', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 5, 31, 9, 47, 48, 699752, tzinfo=utc)),
        ),
    ]
