# Generated by Django 2.2.1 on 2019-06-04 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bloody', '0004_auto_20190603_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='lat',
            field=models.IntegerField(default=28.6282231),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blood',
            name='lng',
            field=models.IntegerField(default=77.389849),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blood',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 6, 4, 10, 2, 4, 23783, tzinfo=utc)),
        ),
    ]
