# Generated by Django 2.2.1 on 2019-06-04 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bloody', '0005_auto_20190604_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 6, 4, 10, 46, 0, 787574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blood',
            name='lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blood',
            name='lng',
            field=models.CharField(max_length=100),
        ),
    ]
